### ISSUE TITLE
Приложение вылетает при нажатии на кнопку "Собрать ПК" 

### ISSUE THREAD

**Issue by sSkorodumov** [ZiminVladimir/SuperConfigurator#4]
Запускаю приложение, нажимаю на "Собрать ПК"
![Рисунок1](https://user-images.githubusercontent.com/71598417/103224059-40daa800-4938-11eb-8a52-0d3df811a159.jpg)
![Рисунок2](https://user-images.githubusercontent.com/71598417/103224178-61a2fd80-4938-11eb-918b-ee0e5e1d84fa.jpg)
Ожидаемое поведение: появление окна конфигурации

**Comment by ZiminVladimir** [comment]
Исправлено
