### ISSUE TITLE
Приложение вылетает, если ввести отрицательное число в бюджет на видеокарту

### ISSUE THREAD

**Issue by sSkorodumov** [ZiminVladimir/SuperConfigurator#5]
![yf03ND1hEZk](https://user-images.githubusercontent.com/71598417/103224448-bc3c5980-4938-11eb-9214-57ca3a1e39a2.jpg)
![BLfpBqJBILw](https://user-images.githubusercontent.com/71598417/103224464-c199a400-4938-11eb-99a3-2d4c8f3463f3.jpg)
Ожидаемое поведение: появление сообщения о невозможном вводе

**Comment by ZiminVladimir** [comment]
Исправлено
