### ISSUE TITLE
Приложение вылетает, если ввести сумму 222222

### ISSUE THREAD

**Issue by sSkorodumov** [ZiminVladimir/SuperConfigurator#6]
![m-SqEKQsr9s](https://user-images.githubusercontent.com/71598417/103224676-340a8400-4939-11eb-90bb-1006e924e712.jpg)
![-2jsNiGiZFY](https://user-images.githubusercontent.com/71598417/103224691-3d93ec00-4939-11eb-9c21-7505b6d784b4.jpg)
Ожидаемое поведение: расчёт конфигурации ПК

**Comment by ZiminVladimir** [comment]
Исправлено
