### ISSUE TITLE
При составлении бюджета с нулевой суммой на видеокарту игнорирует данное значение

### ISSUE THREAD

**Issue by AlexeyVeselov2020** [ZiminVladimir/SuperConfigurator#7]
1. Вводим любую сумму в бюджет. 0 в бюджет на видеокарту
![VCsapnDWGl4](https://user-images.githubusercontent.com/71597683/103237530-ec93f000-4958-11eb-818f-5c38dca26d37.jpg)
2. Получаем результат с видео картой в пределах бюджета
Ожидаемое поведение: предоставить результат без видеокарты или показать сообщение о недопустимости суммы

**Comment by ZiminVladimir** [comment]
Исправлено.
