### ISSUE TITLE
Неправильная реакция на требование SSD с нестандартной ёмкостью

### ISSUE THREAD

**Issue by AlexeyVeselov2020** [ZiminVladimir/SuperConfigurator#8]
1.Вводим любой бюджет и нестандартную ёмкость у SSD.
![ofTfTI8VbJ8](https://user-images.githubusercontent.com/71597683/103237772-b3a84b00-4959-11eb-941b-a4d6695fe768.jpg)
2. Выдаёт конфигурацию с SSD меньшего объёма.
Ожидаемое поведение: уведомить что SSD с такой ёмкостью нет или предложить с большей ёмкостью(остаток по бюджету на скрине больше 20%)

**Comment by ZiminVladimir** [comment]
Исправлено.
