### ISSUE TITLE
Поля второстепенных условий не очищаются при их сокрытие от пользователя

### ISSUE THREAD

**Issue by AlexeyVeselov2020** [ZiminVladimir/SuperConfigurator#9]
1.Вводим любые значения в поля бюджет на процессор, видеокарту и т.д.
![mi1qYpYhhk0](https://user-images.githubusercontent.com/71597683/103238003-6c6e8a00-495a-11eb-96d0-4b237fb55d72.jpg)
2.Скрываем введенные поля с помощью чекбоксов.
![V1qfq1gbtG0](https://user-images.githubusercontent.com/71597683/103238044-8c05b280-495a-11eb-9a20-b99bcecb3f56.jpg)
3.Снова их открываем и видим последние введенные нами значения.
![mi1qYpYhhk0](https://user-images.githubusercontent.com/71597683/103238116-c4a58c00-495a-11eb-93de-33df8ab66d4b.jpg)
Ожидаемое поведение: очистка этих полей от данных при их сокрытии от пользователя.

**Comment by ZiminVladimir** [comment]
Исправлено.
